name: Main Branch Workflow

on:
  workflow_dispatch:

env:
  SDLC_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display branch information
        run: |
          echo "Running with env SDLC_BRANCH: $SDLC_BRANCH"
