name: Main Branch Workflow

on:
  workflow_dispatch:

env:
  BRANCH_NAME: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display branch information
        run: |
          echo "Running with env BRANCH_NAME: $BRANCH_NAME"
