name: PR Validation for Main Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - staging

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: ci
        run: npm install
      
      - name: Check for 'candidate' string in main branch workflow files
        run: npx ts-node ci/workflow-checker.ts