name: PR Validation for Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for 'candidate' string in main branch workflow files
        run: ci/workflow-checkser.sh